use_frameworks!

target 'ICKit_Example' do
  pod 'ICKit/Foundation', :path => '../'
  pod 'ICKit/UIKitEx', :path => '../'
  pod 'ICKit/ResKit', :path => '../'
  pod 'ICKit/TextureEx', :path => '../'
  pod 'ICKit/WcdbEx', :path => '../'

end
